maxday/lambda-perf

s3-uploader/runtimes/go_on_provided/Dockerfile
Go on the Provided AL2 system doesn't require the RPC code that's in the Lambda SDK.
The aws-lambda-go library supports a build tag that strips this unused code from the package with the aim of improving cold start performance, since the unused code strips around 2MB from the output binary.
=> feat(go_on_provided): use -tags lambda.norpc build tag

.github/dependabot.yml
- add dependabot for report-log-processor (see #113)
- change to daily for runtimes (as it could impact cold start)
- change to monthly for the app (as it does not impact anything)
=> change dependabot frequency

manifest.json, s3-uploader/runtimes/java11/build.gradle, s3-uploader/runtimes/java11/src/main/java/io/github/maxday/Handler.java, s3-uploader/runtimes/java11_snapstart/build.gradle, s3-uploader/runtimes/java11_snapstart/src/main/java/io/github/maxday/Handler.java, s3-uploader/runtimes/java17/src/main/java/io/github/maxday/Handler.java, s3-uploader/runtimes/java17_snapstart/build.gradle, s3-uploader/runtimes/java17_snapstart/src/main/java/io/github/maxday/Handler.java, s3-uploader/runtimes/java8/build.gradle, s3-uploader/runtimes/java8/src/main/java/io/github/maxday/Handler.java
This PR extends https://github.com/maxday/lambda-perf/pull/410 to all other java functions
=> update java8, 11, 17 + snapstart to remove runtime

README.md, manifest.json, s3-uploader/runtimes/python311/build.sh, s3-uploader/runtimes/python311/index.py
https://aws.amazon.com/blogs/compute/python-3-11-runtime-now-available-in-aws-lambda/
=> Add support for Python 3.11

function-deployer/app.js, function-trigger-deployer/app.js, manifest.json, s3-uploader/runtimes/bun/build.sh, s3-uploader/runtimes/bun/index.js, serverless.yaml
This PR:
- adds the `layer` field support on the manifest (single value, no need for an array for now)
- adds `lambda:GetLayerVersion` IAM permission since it's needed to deploy a function using a layer
- adds support for bun
fix for #602
=> Add bun support

s3-uploader/runtimes/cpp11/Dockerfile
This PR updates the Dockerfile to use `provided.al2` (ref: https://github.com/maxday/lambda-perf/pull/724)
This allows to make sure that GLIBC version will always be compatible
Note that cmake version was incompatible so I didn't find other solution but to compile it
=> use provided.al2 for cpp

s3-uploader/runtimes/cpp11/lambda/CMakeLists.txt
Technically we should be using the `lambda/provided:al2` container image to do this safely.
But since the Lambda function does not do anything except return "OK", There's a good change this might just work.
Fixes #711
=> Optimize the C++ cold start by decreasing the size of the package

s3-uploader/runtimes/cpp11/Dockerfile
rm lib/* from the package as all libs are already present on provided.al2 image (see #727)
=> rm lib as they're not needed any more

s3-uploader/runtimes/cpp11/Dockerfile, s3-uploader/runtimes/cpp11/lambda/CMakeLists.txt
By building and linking libcurl statically, we minimize the number of libraries that need to be dynamically linked, thereby reducing the cold start time.
=> Build libcurl as a static library for C++ Lambda runtime

s3-uploader/runtimes/cpp11_on_provided_al2/lambda/main.cpp, s3-uploader/runtimes/cpp11_on_provided_al2023/lambda/main.cpp
This eliminates a bunch of unnecessary copying of fields like headers, payload, etc.
=> [C++] Pass the request by reference

README.md, manifest.json, s3-uploader/runtimes/nodejs20x/build.sh, s3-uploader/runtimes/nodejs20x/index.js
AWS added support for Node.js 20 in the past few days.
- [aws-sdk release](https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.446.0)
- [PR for aws-cdk](https://github.com/aws/aws-cdk/pull/27897)
Related [comment from AWS](https://github.com/aws/aws-lambda-base-images/issues/91#issuecomment-1737694321).
=> Add `nodejs20.x`

s3-uploader/runtimes/java11/build.gradle, s3-uploader/runtimes/java11_snapstart/build.gradle, s3-uploader/runtimes/java17/build.gradle, s3-uploader/runtimes/java17_snapstart/build.gradle, s3-uploader/runtimes/java21/build.gradle, s3-uploader/runtimes/java21_snapstart/build.gradle
All Java runtimes > 8 were configured with source- and targetCompatibility 1.8 (java 8).
This means the bytecode produced by the project is java 8 compatible and cant make use of optimizations done in newer java versions. This might have a slight influence on the startup time
=> Fix source/targetCompatibility of java >8 runtimes

s3-uploader/runtimes/dotnet6/src/LambdaPerf.csproj
This is following the typical practice when creating a dotnet lambda from the AWS template:
https://github.com/aws/aws-lambda-dotnet/blob/2eb29ad5de3910677040b14c53f1e3f79f611453/Blueprints/BlueprintDefinitions/vs2022/EmptyFunction/template/src/BlueprintBaseName.1/BlueprintBaseName.1.csproj#L11
=> Use ReadyToRun on dotnet6 lambda

s3-uploader/runtimes/rust_on_provided_al2/Cargo.toml, s3-uploader/runtimes/rust_on_provided_al2023/Cargo.toml
Strip debuginfo for Rust runtime to reduce binary size. For the Rust AL2 runtime it reduced the binary size by about 18.18% (1.1 MB -> 929 KB). See relevant article: https://kobzol.github.io/rust/cargo/2024/01/23/making-rust-binaries-smaller-by-default.html
=> Strip debuginfo for Rust runtime to reduce binary size

.gitignore, s3-uploader/runtimes/dotnet8_aot_on_provided_al2023/Dockerfile, s3-uploader/runtimes/dotnet8_aot_on_provided_al2023/src/aws-lambda-tools-defaults.json
Improve cold start performance for .NET 8 when HTTPS requests are made on Amazon Linux 2023.
See https://github.com/aws/aws-lambda-dotnet/pull/1661.
=> Improve cold starts on AL2023

s3-uploader/runtimes/rust_on_provided_al2/Cargo.toml, s3-uploader/runtimes/rust_on_provided_al2023/Cargo.toml
I released the change to strip the 'debuginfo', but then realized we can also strip symbols as well to reduce the binary size even further. On my machine I saw the binary size reduce from 927kb -> 637kb by stripping symbols in addition to debuginfo. An additional 31.2% drop in binary size beyond the drop from stripping only the debuginfo.
Reference: https://doc.rust-lang.org/cargo/reference/profiles.html#strip
=> Strip symbols and debuginfo from Rust runtime to reduce binary size

s3-uploader/runtimes/java21_snapstart/build.gradle, s3-uploader/runtimes/java21_snapstart/src/main/java/io/github/maxday/Handler.java
This is a tough benchmark for Lambda SnapStart. It caches snapshots so the first restore of a Lambda version is always slower than future ones. 
One technique to improve the first restore latency is to have the JVM load and initialize classes before the snapshot is taken. This can be done using the CRaC APIs. In this PR I've made a before hook that does the same thing as the handler. It will mean that those classes are already compiled and stored in the snapshot when the handler is invoked.
=> Java 21 SnapStart Priming

s3-uploader/runtimes/go_on_provided_al2/go.mod, s3-uploader/runtimes/go_on_provided_al2023/go.mod
The previously used 1.19 was the first release after generics addition so there was certain performance impact. The newer versions are gaining back the speed, so would be interesting to see how 1.22 performs.
Update aws-lambda-go dependency to latest while here.
=> Update Golang version to 1.22.

s3-uploader/runtimes/go_on_provided_al2/go.mod, s3-uploader/runtimes/go_on_provided_al2023/go.mod
fix for
go: download go1.22 for linux/amd64: toolchain not available
=> fix go to prevent missing toolchain error

.github/workflows/aws-deploy.yml, Cargo.toml, serverless.yaml
- add a 7days retention filter on log groups
- remove cron trigger for stagging
=> add log retention

.github/workflows/aws-deploy.yml
add serverless v4 to be able to use node22
=> bump: sls v4

s3-uploader/runtimes/graalvm_java17_on_provided_al2/pom.xml
`no-fallback` is not recognized as an option anymore and the build was failing, this PR removes it
=> fix: no-fallback was failing in graalvm17

s3-uploader/runtimes/rust_on_provided_al2/Dockerfile
simplify the Dockerfile to use cargo release directly.
previously linked GLIBC version was incorrect and incompatible with al2
=> fix: rust al2

common_lib/src/report_log.rs, function-report-log-processor-rs/src/main.rs
before:
- if an error happens in a batch, all subsequent messages will be drop
after:
- log and continue
=> fix: error in log reporter

s3-uploader/runtimes/graalvm_java17_on_provided_al2/pom.xml, s3-uploader/runtimes/graalvm_java21_on_provided_al2023/pom.xml
fix: `The current machine does not support all of the following CPU features that are required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].
Please rebuild the executable with an appropriate setting of the -march option.`
=> fix: arch for graalvm

.github/workflows/autobuild.yml, .github/workflows/aws-deploy.yml, .github/workflows/aws-publish-artifact-to-ecr.yml, .github/workflows/aws-publish-artifact-to-s3.yml, .github/workflows/push-to-ecr.yml, .github/workflows/push-to-s3.yml, .github/workflows/test.yml
don't expose region, use secrets, make them configurable in workflows
=> feat: dynamic region
