.github/workflows/aws-deploy.yml
.github/workflows/deploy.yml
serverless.yaml

add github actions to automate the deployment workflow

add GitHub actions

---

s3-uploader/runtimes/java17/build.gradle
s3-uploader/runtimes/java17/src/main/java/io/github/maxday/Handler.java

**Before**
Init | Duration
-- | --
381.68 | 9.64
413.96 | 21.44
390.73 | 20.61
401.89 | 17.30
427.39 | 17.06
Average Init 403.13ms
Average Duration 17.21ms
**After**
Init | Duration
-- | --
194.12 | 1.52
216.75 | 1.78
258.31 | 1.52
204.87 | 1.72
209.18 | 1.83
Average Init 216.65ms
Average Duration 1.67ms

Remove unused code for 'hello world'

---

manifest.json
s3-uploader/runtimes/dotnet7_aot_on_provided_al2/Dockerfile
s3-uploader/runtimes/dotnet7_aot_on_provided_al2/build.sh

.NET 7 Native AOT is now supported on ARM. This adds that configuration.

Add .NET7 Native AOT ARM

---

function-invoker/app.js
function-trigger-deployer/app.js

handle retries in removePermission

handle errors remove permission

---

result-builder/app.js

fix regex + add missing params

fix prevent cache

---

.github/workflows/aws-s3-uploader.yml
s3-uploader/app.mjs

This PR 
- runs `docker system prune --all` to prevent workers to go out of space
- remove useless folder structure
- adds debug logs

Fix Out Of Space issue

---

s3-uploader/runtimes/cpp11/Dockerfile

- install cmake3 instead of cmake
- get rid of the useless compilation of cmake

use cmake3

---

common_lib/src/lambda_manager.rs
common_lib/src/manifest.rs
common_lib/src/report_log.rs
common_lib/src/runtime.rs
common_lib/src/sqs_manager.rs
function-invoker-rs/src/main.rs
function-trigger-deployer-rs/src/main.rs
result-builder/app.js

- refactor runtime
- refactor common_lib
- add unit tests

refactor runtime and common_lib

---

docs/css/custom.css

My proposal to implement https://github.com/maxday/lambda-perf/issues/263
If the user requested dark mode via their browser or OS settings a dark color scheme is applied

Proposal to implement dark mode

---

s3-uploader/runtimes/quarkus_native_on_provided_al2/src/main/resources/application.properties

fix sporadic failures Quarkus Native

---

README.md
manifest.json
s3-uploader/runtimes/graalvm_java21_on_provided_al2/Dockerfile
s3-uploader/runtimes/graalvm_java21_on_provided_al2/build.sh
s3-uploader/runtimes/graalvm_java21_on_provided_al2/pom.xml
s3-uploader/runtimes/graalvm_java21_on_provided_al2/src/main/java/com/xavierbouclet/OkHandler.java
s3-uploader/runtimes/graalvm_java21_on_provided_al2/src/main/resources/reflect.json

This PR adds a specific runtime for GraalVM - Java 21 to the ones already existing.

Add GraalVM Java 21

---

README.md
manifest.json
s3-uploader/runtimes/ruby33/build.sh
s3-uploader/runtimes/ruby33/index.rb

add ruby 3.3

---

result-builder/app.mjs
result-builder/package.json
serverless.yaml

bump resultBuilder to nodejs20
change js to mjs

bump resultBuilder to nodejs20

---

serverless.yaml

control plane:
bump provided.al2 -> provided.al2023
bump nodejs20x -> nodejs22x

feat: use al2023 and node22.x for the control plane

---

cdk/lib/role.ts

fix: GetLayerVersion role

---

cdk/lib/lambda-perf-stack.ts
function-invoker-rs/src/main.rs

fix: resource conflict exception

---

README.md
manifest.json
s3-uploader/runtimes/python313/build.sh
s3-uploader/runtimes/python313/index.py

feat(python3.13): add python3.13 runtime

---

Cargo.lock
common_lib/Cargo.toml
common_lib/src/dynamodb_manager.rs
common_lib/src/lambda_manager.rs
common_lib/src/retry_manager.rs
common_lib/src/runtime.rs
function-deployer-rs/Cargo.toml
function-deployer-rs/src/main.rs
function-invoker-rs/Cargo.toml
function-invoker-rs/src/main.rs
function-report-log-processor-rs/Cargo.toml
function-report-log-processor-rs/src/main.rs
function-trigger-deployer-rs/Cargo.toml
function-trigger-deployer-rs/src/main.rs
s3-uploader/runtimes/rust_on_provided_al2/Cargo.toml
s3-uploader/runtimes/rust_on_provided_al2023/Cargo.toml

migrate to rust edition 2024
remove useless lifetime

feat: migrate rust 2024

---

s3-uploader/runtimes/rust_on_provided_al2/Dockerfile

-no need to install openssl anymore
-fix warning casing error

fix: no need to install openssl anymore

---

README.md
s3-uploader/runtimes/graalvm_java23_on_provided_al2023/pom.xml

- fix build args 
- udpate readme

fix: build args graalvm java23 and update readme

---

.github/workflows/autobuild.yml
.github/workflows/push-to-ecr.yml
.github/workflows/push-to-s3.yml
.github/workflows/test.yml

fix: secrets for dependabot

---

.github/workflows/push-to-s3.yml

update secrets logic in GitHub actions

fix: secrets

---

README.md

*Description of changes:*
Small PR - Commit 55373175e2a83114776bb45c47fa5fc1b41dbd42 moved `2022-09-05.json`. This PR adjusts sources to changes.

Update JSON input example

---

README.md
manifest.json
s3-uploader/runtimes/ruby34/build.sh
s3-uploader/runtimes/ruby34/handler.rb

*Issue #, if available:*
*Description of changes:*
Adding support for ruby3.4 managed runtimes
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

feat: add ruby3.4

---

.github/dependabot.yml

This should trigger dependabot PR for dev-dependencies
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

feat: use dependency type for dependabot
